POST http://localhost:3000/api/login
Content-Type: application/json

{
  "login": "admin",
  "password": "password"
}

###

GET http://localhost:3000/api/ HTTP/1.1

###

GET http://localhost:3000/api/10 HTTP/1.1

